apiVersion: v1
kind: Pod
metadata:
  name: lab-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: lab-pvc
  containers:
    - name: lab-pod
      image: nginx
      ports:
        - containerPort: 80
          name: lap-pod
      volumeMounts:
        - mountPath: /usr/share/nginx/html
