apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: myreplicaset
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: web
    spec:
      containers:
        - name: nginx-deploy
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: web