## this is the example of NodePort
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
spes:
  type: NodePort
  ports:
    - name: http #service port
      port: 80
      targetPort: 80 # pods port
      nodePort: 3200 #nodes port
      protocol: TCP
  selector:
    app: nginx
