apiVersion: apps/v1
kind: Deployemnt
metadata:
  name: deployments-busybox-image
  labels:
    app: busybox
spec:
  template:
    metadata:
      name: busybox-app
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox-deploy
          image: busybox
          command:
            - sleep
            - "3600"
  replicas: 3
  selector:
    matchLabels:
      app: busybox