apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment
    labels:
      k8s-app: kube-dns
spec:
  template:
    metadata:
      name: nginx
      labels:
        k8s-app: kube-dns
    spec:
      containers:
        - name: nginx
          image: nginx:1.8
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
  selector:
    matchLabels:
      k8s-app: kube-dns