apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment
    labels:
      service: nginx
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: webshop
    spec:
      containers:
        - name: nginx
          image: nginx:1.8
  replicas: 5
  startegy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1  
  selector:
    matchLabels:
      app: webshop