apiVersion: v1
kind: Service
metadata:
  name: sample-deployment-service
  namespace: kube-system
  labels:
    app: sample-deployment
spec:
  selector:
    app: sample-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80