apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    type: fargate
spec:
  template:
    metadata:
      name: my-first-pod
      labels:
        app: nginx
        type: fargate
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      type: fargate
 