apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-app
  rules:
  - http:
      paths:
      - path: /ingress
        pathType: Prefix
        backend:
          service:
            name: svc-app
            port:
              number: 80